// src/components/answer.svelte
<script lang="ts">
  import { cubicIn, cubicOut } from "svelte/easing"
  import type { TransitionConfig } from "svelte/transition"

  import { usePatch } from "#/hooks/patch.svelte.ts"

  const patchState = usePatch()

  let displayed = $state(patchState.recentlyReleased)
  let pending = $state(patchState.recentlyReleased)
  let visible = $state(true)

  $effect(() => {
    pending = patchState.recentlyReleased

    if (pending !== displayed && visible) {
      visible = false
    }
  })

  function enterFromLeft(_?: unknown): TransitionConfig {
    return {
      duration: 250,
      easing: cubicOut,
      css: (t) => `
        opacity: ${t};
        transform: translateX(${(1 - t) * -100}%);
      `,
    }
  }

  function leaveToRight(_?: unknown): TransitionConfig {
    return {
      duration: 250,
      easing: cubicIn,
      css: (t) => `
        opacity: ${t};
        transform: translateX(${(1 - t) * 100}%);
      `,
    }
  }

  function handleOutroEnd() {
    displayed = pending
    visible = true
  }
</script>

<div class="align-center pointer-events-none relative flex font-serif">
  {#if visible}
    <h1 class="m-0 my-4 text-8xl" in:enterFromLeft out:leaveToRight onoutroend={handleOutroEnd}>
      {displayed ? "Yes!" : "No."}
    </h1>
  {/if}
</div>

// src/components/answer.vue
<template>
  <div
    class="flex relative align-center font-serif text-10xl md:text-12xl pointer-events-none"
  >
    <transition
      mode="out-in"
      class="duration-250"
      enter-active-class="ease-out"
      leave-active-class="ease-in"
      enter-from-class="transform -translate-x-full opacity-0"
      leave-to-class="transform translate-x-full opacity-0"
    >
      <div v-if="released" key="true">Yes!</div>
      <div v-else key="false">No.</div>
    </transition>
  </div>
</template>

<script lang="ts" setup>
import { defineProps } from "vue"

defineProps<{ released: boolean }>()
</script>
