// src/components/bottom-bar/notifications.vue
<template>
  <ToggleButton circle :checked="subscribed" class="text-base" @change="handleChange">
    <Icon
      class="h-5 w-5 mr-2 hover:fill-gray-100 animate-infinite animate-slow transition-all"
      :class="iconClasses"
      :icon="subscribed ? alertSvg : noAlertSvg"
    />

    {{ subscribed ? "Disable" : "Enable" }} notifications
  </ToggleButton>
</template>

<script lang="ts" setup>
import { computed } from "vue"

import alertSvg from "../../assets/alert.svg?raw"
import noAlertSvg from "../../assets/no-alert.svg?raw"
import { usePushNotifications } from "../../hooks/use-push-notifications"
import ToggleButton from "../toggle-button.vue"

import Icon from "./icon.vue"

const { supported, loading, subscribing, subscribed, askForPermissions, unsubscribe } =
  usePushNotifications()

const iconClasses = computed(() => ({
  "animate-heartBeat": subscribing.value,
  "grayed-out": !supported || loading.value,
  "fill-gray-400": !subscribed.value,
  shine: subscribed.value,
}))

const handleChange = () => {
  if (subscribed.value) {
    return unsubscribe()
  }

  void askForPermissions()
}
</script>

<style scoped>
.shine {
  filter: drop-shadow(0 0 4px #ccc);
}
</style>

// src/components/notifications.svelte
<script lang="ts">
  import { usePushNotifications } from "#/hooks/notifications.svelte.ts"
  import { browser } from "$app/env"

  const notifications = usePushNotifications()

  const toggleSubscribed = () => {
    !notifications.state.subscribed ? notifications.enable() : notifications.disable()
  }

  // ... or if it's being rendered on the server
  const supportsNotifications = $derived(!browser || notifications.supported)
</script>

<button
  onclick={toggleSubscribed}
  class="bg-trans b-0 text-#eee flex cursor-pointer items-center rounded-xl px-3 font-sans text-lg select-auto"
  class:grayed-out={!supportsNotifications}
  class:pointer-events-none={!supportsNotifications}
>
  <i
    class="animate-infinite animate-slow color-white mr-2 size-6 transition-all"
    class:animate-heartBeat={notifications.state.subscribing}
    class:fill-gray-400={notifications.state.subscribed}
    class:shine={notifications.state.subscribed}
    class:i-lucide:bell={!notifications.state.subscribed}
    class:i-lucide:bell-off={notifications.state.subscribed}
  ></i>

  {#if supportsNotifications}
    {!notifications.state.subscribed ? "Enable" : "Disable"} push notifications
  {:else}
    Device doesn't support notifications.
  {/if}
</button>
