// src/components/question.vue
<template>
  <div
    class="flex flex-col md:flex-row md:items-center md:gap-2 text-2xl md:text-4xl font-serif text-center"
  >
    Is

    <div
      v-for="(patch, i) in relevantPatches"
      :key="patch?.toString()"
      class="md:flex md:items-center md:gap-2"
    >
      <span v-if="i !== 0">{{ " " }}or{{ " " }}</span>

      <span class="font-bold text-5xl md:text-7xl text-primary-500">
        {{ patch?.toString() }}
      </span>
    </div>

    out yet?
  </div>
</template>

<script lang="ts" setup>
import { DotaPatchType, DotaVersion } from "dotaver"
import { computed } from "vue"

import type { Patch } from "../types"

const props = defineProps<{
  recentlyReleased: boolean
  latestPatch: Patch
}>()

const currentPatch = computed(() => DotaVersion.parse(props.latestPatch.id))
const nextPatches = computed(() => [
  currentPatch.value.next(DotaPatchType.Minor),
  currentPatch.value.next(DotaPatchType.Patch),
])

const relevantPatches = computed(() =>
  props.recentlyReleased ? [DotaVersion.parse(props.latestPatch.id)] : nextPatches.value,
)
</script>

// src/components/question.svelte
<script lang="ts">
  import { DotaPatchType, DotaVersion } from "dotaver"

  import { usePatch } from "#/hooks/patch.svelte.ts"

  const patchState = usePatch()

  const currentPatch = $derived(DotaVersion.parse(patchState.patch!.id))
  const nextPatches = $derived([
    currentPatch.next(DotaPatchType.Minor),
    currentPatch.next(DotaPatchType.Patch),
  ])

  const relevantPatches = $derived.by(() =>
    patchState.recentlyReleased ? [currentPatch] : nextPatches,
  )
</script>

{#if patchState.patch != null}
  <div
    class="flex flex-col text-center font-serif text-3xl md:flex-row md:items-center md:gap-2 md:text-4xl"
  >
    Is

    {#each relevantPatches as patch, i (patch?.toString())}
      <div class="md:flex md:items-center md:gap-2">
        {#if i !== 0}
          <span> or </span>
        {/if}

        <span class="text-amber-5 text-7xl font-bold">
          {patch?.toString()}
        </span>
      </div>
    {/each}

    out yet?
  </div>
{/if}
